# SPDX-FileCopyrightText: 2025 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "undoredo"
version = "0.3.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Incremental-diff undo-redo decorator for collections such as HashMap, BTreeMap, StableVec, thunderdome::Arena, rstar::RTree. No need to implement commands."
repository = "https://codeberg.org/topola/undoredo"
documentation = "https://docs.rs/undoredo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo", "no_std"]
categories = ["data-structures", "gui", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]
std = []
stable-vec = ["maplike/stable-vec"]
thunderdome = ["maplike/thunderdome"]
rstar = ["maplike/rstar"]

[dependencies]
maplike = "0.5"
rstared = { version = "0.4", optional = true }

[dev-dependencies]
stable-vec = "0.4"
thunderdome = "0.6"
rstar = "0.12"
rstared = "0.3"

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]

[[example]]
name = "basic_usage"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "cmd_commit"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "stable_vec"
required-features = ["stable-vec"]
doc-scrape-examples = true

[[example]]
name = "thunderdome"
required-features = ["thunderdome"]
doc-scrape-examples = true

[[example]]
name = "rstar"
required-features = ["rstar"]
doc-scrape-examples = true
