# SPDX-FileCopyrightText: 2025 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "undoredo"
version = "0.8.5"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Delta-based undo-redo decorator for collections such as HashMap, BTreeMap, StableVec, thunderdome::Arena, rstar::RTree. No need to implement commands."
repository = "https://codeberg.org/topola/undoredo"
documentation = "https://docs.rs/undoredo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo", "no_std"]
categories = ["data-structures", "gui", "no-std", "rust-patterns"]
edition = "2024"

[badges]
maintenance = { status = "actively-developed" }

[features]
derive = ["undoredo_derive"]
default = ["std"]
std = []
rstar = ["dep:rstar", "maplike/rstar"]
rstared = ["dep:rstared", "dep:rstar"]
stable-vec = ["dep:stable-vec", "maplike/stable-vec"]
thunderdome = ["dep:thunderdome", "maplike/thunderdome"]

[dependencies]
maplike = "0.8"
stable-vec = { version = "0.4", optional = true }
rstar = { version = "0.12", optional = true }
rstared = { version = "0.8", optional = true }
thunderdome = { version = "0.6", optional = true }
undoredo_derive = { version = "0.8", optional = true, path = "undoredo_derive" }

[dev-dependencies]
stable-vec = "0.4"
thunderdome = "0.6"
rstar = "0.12"
rstared = "0.8"

[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]

[[example]]
name = "basic_usage"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "cmd_commit"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "stable_vec"
required-features = ["stable-vec"]
doc-scrape-examples = true

[[example]]
name = "thunderdome"
required-features = ["thunderdome"]
doc-scrape-examples = true

[[example]]
name = "rstar"
required-features = ["rstar"]
doc-scrape-examples = true

[[example]]
name = "rstared"
required-features = ["rstared"]
doc-scrape-examples = true
