# SPDX-FileCopyrightText: 2025 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[workspace]
members = [".", "undoredo_derive"]

[package]
name = "undoredo"
version = "0.14.0"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Undo/Redo (and delta encoding) in Rust using deltas, snapshots or commands with convenience implementations for many standard and third-party types."
repository = "https://github.com/mikwielgus/undoredo"
documentation = "https://docs.rs/undoredo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["delta", "diff", "undo", "redo", "no_std"]
categories = ["gui", "compression", "data-structures", "no-std", "rust-patterns"]
edition = "2024"
rust-version = "1.92"

[badges]
maintenance = { status = "actively-developed" }

[features]
default = ["std"]

## Enables the `Delta` derive macro (and also its constituent macros,
## `ApplyDelta`, `FlushDelta`, `HalfDelta`, `MergeDelta`).
derive = ["undoredo_derive"]

## Enables `serde` support (derives `Serialize` and `Deserialize` traits).
serde = ["dep:serde"]

## Disable for `no_std` compatibility.
std = ["maplike/std"]

## Enables support of delta-recording for `bidimap::BiBTreeMap` and `bidimap::BiHashMap`.
bidimap = ["dep:bidimap", "maplike/bidimap"]

## Enables support of delta-recording for `indexmap::IndexMap` and `indexmap::IndexSet`.
indexmap = ["dep:indexmap", "maplike/indexmap"]

## Enables support of delta-recording for `rstar::RTree`.
rstar = ["dep:rstar", "maplike/rstar"]

## Enables support of delta-recording for `rstared::RTreed`. Enables `rstar`
## feature flag as well.
rstared = ["rstar", "dep:rstared"]

## Enables support of delta-recording for `stable_vec::StableVec`.
stable-vec = ["dep:stable-vec", "maplike/stable-vec"]

## Enables support of delta-recording for `thunderdome::Arena`.
thunderdome = ["dep:thunderdome", "maplike/thunderdome"]

## Enables support of delta-recording for `tinyvec::ArrayVec` and `tinyvec::TinyVec`.
tinyvec = ["dep:tinyvec", "maplike/tinyvec"]

[dependencies]
bidimap = { version = "0.7", optional = true }
document-features = { version = "0.2", optional = true }
indexmap = { version = "2.14", optional = true }
maplike = { version = "0.13", default-features = false, features = ["alloc", "derive"] }
rstar = { version = "0.13", optional = true }
rstared = { version = "0.13", optional = true }
serde = { version = "1.0", optional = true, default-features = false, features = ["derive", "alloc"] }
stable-vec = { version = "0.4", optional = true }
thunderdome = { version = "0.6", optional = true }
tinyvec = { version = "1", features = ["alloc"], optional = true }
undoredo_derive = { version = "0.14", optional = true, path = "undoredo_derive" }

[dev-dependencies]
indexmap = "2.14"
rstar = "0.13"
rstared = "0.13"
serde = { version = "1.0", features = ["derive"] }
stable-vec = "0.4"
thunderdome = "0.6"
tinyvec = { version = "1", features = ["alloc"] }
# This enables `derive` on the library, which we need for integration tests.
undoredo = { path = ".", default-features = false, features = ["derive", "std", "indexmap", "tinyvec"] }

# Version replacements apply only to this crate. We have to keep this here
# and not in `release.toml` because the replacements are applied to each
# workspace member crate separately, and since there is nothing to replace in
# `undoredo_derive`, there will be an error due to no replacement. This solution
# is recommended by `cargo-release`'s FAQ.
[package.metadata.release]
pre-release-hook = [
  "cargo",
  "semver-checks",
  "check-release",
  "-p",
  "{{crate_name}}",
  "--baseline-version",
  "{{prev_version}}",
]
pre-release-replacements = [
  { file = "README.md", search = 'undoredo = \{ version = "[^"]+"([^}]*)\}', replace = '{{crate_name}} = { version = "{{version}}"$1}' },
]

# Use scraped examples.
[package.metadata.docs.rs]
cargo-args = ["--all-features", "-Zunstable-options", "-Zrustdoc-scrape-examples"]
rustdoc-args = ["--cfg", "docsrs"]

[[example]]
name = "basic_usage"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "bihashmap"
required-features = ["bidimap"]
doc-scrape-examples = true

[[example]]
name = "cmd_commit"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "commands"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "entities"
required-features = ["std", "derive"]
doc-scrape-examples = true

[[example]]
name = "history_tree"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "rstar"
required-features = ["rstar"]
doc-scrape-examples = true

[[example]]
name = "rstared"
required-features = ["rstared"]
doc-scrape-examples = true

[[example]]
name = "snapshots"
required-features = ["std"]
doc-scrape-examples = true

[[example]]
name = "stable_vec"
required-features = ["stable-vec"]
doc-scrape-examples = true

[[example]]
name = "thunderdome"
required-features = ["thunderdome"]
doc-scrape-examples = true
