// SPDX-FileCopyrightText: 2026 undoredo contributors
//
// SPDX-License-Identifier: MIT OR Apache-2.0

use std::ops::Add;

use undoredo::{Recorder, UndoRedo};
use undoredo_derive::Delta;

// No need for `#[derive(Delta)]` for types stored in containers, only the
// containers themselves need this.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Vector2<K> {
    x: K,
    y: K,
}

impl<K: Add<K, Output = K>> Add for Vector2<K> {
    type Output = Self;

    fn add(self, rhs: Self) -> Self {
        Self {
            x: self.x + rhs.x,
            y: self.y + rhs.y,
        }
    }
}

// `#[derive(Delta)]` will generate the `EntitiesDelta` type, which we store in
// as an edit in the `UndoRedo` bistack.
#[derive(Delta)]
pub struct Entities<K> {
    positions: Recorder<Vec<Vector2<K>>>,
    velocities: Recorder<Vec<Vector2<K>>>,
    healths: Recorder<Vec<i64>>,
}

impl<K: Add<K, Output = K> + Copy + PartialOrd> Entities<K> {
    pub fn new_entity(&mut self, position: Vector2<K>, velocity: Vector2<K>, health: i64) -> usize {
        self.positions.push(position);
        self.velocities.push(velocity);
        self.healths.push(health)
    }

    pub fn update_entities(&mut self) {
        for i in 0..self.positions.container().len() {
            self.update_entity(i);
        }
    }

    fn update_entity(&mut self, index: usize) {
        // Add velocitiey to positions on every update.
        self.positions.set(
            index,
            *self.positions.get(&index).unwrap() + *self.velocities.get(&index).unwrap(),
        );

        // Decrease health by 1 on every update.
        self.healths
            .set(index, self.healths.get(&index).unwrap() - 1);
    }
}

fn assert_entity(entities: &Entities<f64>, index: usize, pos: Vector2<f64>, health: i64) {
    assert_eq!(*entities.positions.get(&index).unwrap(), pos);
    assert_eq!(*entities.healths.get(&index).unwrap(), health);
}

fn main() {
    let mut entities = Entities::<f64> {
        positions: Recorder::new(Vec::new()),
        velocities: Recorder::new(Vec::new()),
        healths: Recorder::new(Vec::new()),
    };

    // `EntitiesDelta<K>` was generated by `#[derive(Delta)]` on `Entities`.
    let mut undoredo: UndoRedo<EntitiesDelta<f64>> = UndoRedo::new();

    entities.new_entity(Vector2 { x: 0.0, y: 0.0 }, Vector2 { x: 1.0, y: 0.0 }, 100);
    entities.new_entity(Vector2 { x: 0.0, y: 0.0 }, Vector2 { x: 0.0, y: 2.0 }, 100);
    undoredo.commit(&mut entities);

    entities.new_entity(
        Vector2 { x: 100.0, y: 100.0 },
        Vector2 { x: -1.0, y: -1.0 },
        50,
    );
    undoredo.commit(&mut entities);

    assert_eq!(entities.positions.container().len(), 3);

    // Perform three simulation updates.
    for _ in 0..3 {
        entities.update_entities();
        undoredo.commit(&mut entities);
    }

    assert!(entities.positions.container().len() == 3);
    assert_entity(&entities, 0, Vector2 { x: 3.0, y: 0.0 }, 97);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 6.0 }, 97);
    assert_entity(&entities, 2, Vector2 { x: 97.0, y: 97.0 }, 47);

    assert!(undoredo.undo(&mut entities).is_some());
    assert!(entities.positions.container().len() == 3);
    assert_entity(&entities, 0, Vector2 { x: 2.0, y: 0.0 }, 98);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 4.0 }, 98);
    assert_entity(&entities, 2, Vector2 { x: 98.0, y: 98.0 }, 48);

    assert!(undoredo.undo(&mut entities).is_some());
    assert!(entities.positions.container().len() == 3);
    assert_entity(&entities, 0, Vector2 { x: 1.0, y: 0.0 }, 99);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 2.0 }, 99);
    assert_entity(&entities, 2, Vector2 { x: 99.0, y: 99.0 }, 49);

    assert!(undoredo.undo(&mut entities).is_some());
    assert!(entities.positions.container().len() == 3);
    assert_entity(&entities, 0, Vector2 { x: 0.0, y: 0.0 }, 100);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 0.0 }, 100);
    assert_entity(&entities, 2, Vector2 { x: 100.0, y: 100.0 }, 50);

    assert!(undoredo.undo(&mut entities).is_some());
    assert!(entities.positions.container().len() == 2);
    assert_entity(&entities, 0, Vector2 { x: 0.0, y: 0.0 }, 100);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 0.0 }, 100);

    assert!(undoredo.redo(&mut entities).is_some());
    assert!(entities.positions.container().len() == 3);
    assert_entity(&entities, 0, Vector2 { x: 0.0, y: 0.0 }, 100);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 0.0 }, 100);
    assert_entity(&entities, 2, Vector2 { x: 100.0, y: 100.0 }, 50);

    assert!(undoredo.redo(&mut entities).is_some());
    assert_entity(&entities, 0, Vector2 { x: 1.0, y: 0.0 }, 99);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 2.0 }, 99);
    assert_entity(&entities, 2, Vector2 { x: 99.0, y: 99.0 }, 49);

    assert!(undoredo.redo(&mut entities).is_some());
    assert_entity(&entities, 0, Vector2 { x: 2.0, y: 0.0 }, 98);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 4.0 }, 98);
    assert_entity(&entities, 2, Vector2 { x: 98.0, y: 98.0 }, 48);

    assert!(undoredo.redo(&mut entities).is_some());
    assert_entity(&entities, 0, Vector2 { x: 3.0, y: 0.0 }, 97);
    assert_entity(&entities, 1, Vector2 { x: 0.0, y: 6.0 }, 97);
    assert_entity(&entities, 2, Vector2 { x: 97.0, y: 97.0 }, 47);

    assert!(undoredo.redo(&mut entities).is_none());
}

#[test]
fn test() {
    main();
}
