# SPDX-FileCopyrightText: 2026 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

[package]
name = "undoredo_derive"
version = "0.10.3"
authors = ["Mikolaj Wielgus <wielgusmikolaj@gmail.com>"]
description = "Derive macros for undoredo."
repository = "https://github.com/mikwielgus/undoredo"
documentation = "https://docs.rs/undoredo"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["undo", "redo", "no_std"]
categories = ["data-structures", "gui", "no-std", "rust-patterns"]
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = { version = "2", features = ["full"] }

[dev-dependencies]
# This enables `derive` and `std` on the library, which we need for integration
# tests.
undoredo = { path = "..", default-features = true, features = ["derive", "std"] }
maplike = "0.9"
