# SPDX-FileCopyrightText: 2025 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

steps:
  check_licensing:
    image: fsfe/reuse
    commands:
      - reuse lint
    when:
      event: [pull_request, push, tag]
