# SPDX-FileCopyrightText: 2025 undoredo contributors
#
# SPDX-License-Identifier: MIT OR Apache-2.0

matrix:
  CHANNEL:
    - stable
    - nightly
  FEATURE_FLAGS:
    - --no-default-features
    - --features stable-vec
    - --features thunderdome
    - --features rstar
    - --features rstared
    - --all-features

steps:
  test:
    image: rust
    environment:
      RUST_BACKTRACE: 1
      CARGO_TEST_COLOR: always
    commands:
      - rustup default "$CHANNEL"
      - cargo test -j4 --all-targets $FEATURE_FLAGS
      - cargo test -j4 --doc $FEATURE_FLAGS
    when:
      event: [pull_request, push, tag]
